# Generated by Django 2.2.1 on 2019-07-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190725_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='heading',
            field=models.TextField(default='', max_length=200),
        ),
    ]
